/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Starting Qcalc..");
        StandardCalculator calc = new StandardCalculator();
        calc.divide(2.2,1.0);
        calc.printResult();
    }
}
